# Generated by Django 4.0.3 on 2022-06-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_item_amount_item_unit_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('drinks', 'DRINKS'), ('dairy', 'DAIRY'), ('dessert', 'DESSERT'), ('fruit', 'FRUIT'), ('grains', 'GRAINS'), ('meat', 'MEAT'), ('vegetables', 'VEGETABLES')], default='drinks', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
