# Generated by Django 4.0.3 on 2022-05-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='tracker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trackers.tracker'),
            preserve_default=False,
        ),
    ]
