# Generated by Django 4.0.3 on 2022-05-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_data_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='title',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
