# Generated by Django 4.0.3 on 2022-05-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0004_remove_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
    ]
