# Generated by Django 4.0.3 on 2022-05-26 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0005_remove_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.DateField(default=django.utils.timezone.localtime),
        ),
    ]
