# Generated by Django 4.0.3 on 2022-06-06 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0008_alter_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('tracker', 'date')},
        ),
    ]
