# Generated by Django 4.0.3 on 2022-03-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_task_creation_date_task_description_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
