# Generated by Django 4.0.3 on 2022-04-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_shopping_list_item_shoppinglist_alter_task_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['text']},
        ),
    ]
