# Generated by Django 4.0.3 on 2022-04-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_item_delete_shopping_list_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='list_title',
            new_name='title',
        ),
    ]
