# Generated by Django 4.0.3 on 2022-05-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_tracker_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
